### ISSUE TITLE
[JOB-STORY] Make 4 Security Level Configuration available (0, 1, 2, 3) complying with IEC 62443.

### ISSUE THREAD

**Issue by AlexHx8472** [TrustPoint-Project/trustpoint#121]
Related to #120 

**Job Story**
When configuring the Trustpoint, I want to to be able to select a Target Security Level, so I can make sure, I'm not using any features of the Trustpoint that could or would undermine that Target Security Level.

**Acceptance Criteria**
- [x] Add the Security Level Configuration to the Trustpoint
- [x] Add Target Security Level 0 (Development / Debug)
- [x] Add Target Security Level 1 (Low)
- [x] Add Target Security Level 2 (Medium)
- [x] Add Target Security Level 3 (High)
- [x] Add Target Security Level 3 (Very High)
- [x] Following the secure by default methodology, the default setting shall be Target Security Level 1

**Note**
The Acceptance Criteria still need refinement / discussion.

**Comment by Aircoookie** [comment]
Note: Target security level 1 is called "Basic", otherwise this is fully implemented.
