### ISSUE TITLE
[JOB-STORY] Allow the use of the local auto-generated Issuing CA only on levels 0 and 1 (Dev/Basic)

### ISSUE THREAD

**Issue by AlexHx8472** [TrustPoint-Project/trustpoint#122]
Related to #120

**Job Story**
When I configure the Target Security Level 0 (Development / Debug) or 1 (Basic), I want to be able to use the auto-generated Issuing CA.
When I configure a Target Security Level > 1, the auto-generated Issuing CA must not be available.

**Acceptance Criteria**
- [x] Switching to the Target Security Level to 0/1, a new auto-generated Issuing CA shall be generated and be usable.
- [x] Add a select box for choosing the signature suite of the auto-generated Issuing CA
- [x] Switching to a higer Target Security Level from Level 0/1 shall
  - [x] Display a warning and confirmation prompt
    - [x] On confirmation:
      - [x] Revoke all certificates issued by the auto-generated Issuing CA
      - [x] Remove the auto-generated Issuing CA as option to act as a Issuing CA everywhere
      - [ ] Hide these certificates everywhere in the frontend
      - [x] Flag those certificates as non-usable

Edit: Updated to SL 0/1 to align with IEC 62443.

**Comment by Aircoookie** [comment]
I just referenced IEC 62443 pt. 3-3 again:
SR 1.9 requires HSM/TPM to be used for SL-C 3+ (and I would also use HSM for auto gen PKI as well if/when available).
SR 1.8 requires that when targeting SL-C 2+ running a PKI it "either must be operated according to industry practices, or the public certificate must be obtained from an external PKI.". Whatever this entails, it is reasonable to assume a fully local PKI without a remote (and ideally offline) root CA is not adhering to (best) industry practices.

In any case, I would still allow the auto-gen PKI in the "Basic" setting, which is supposed to reflect SL1.

**Comment by Aircoookie** [comment]
I do not necessarily fully agree with the requirement "Hide these certificates **everywhere** in the frontend". Current implementation keeps them in the CertificateModel table (as revoked) and I think doing so makes sense.
