### ISSUE TITLE
Add Security Level Settings

### ISSUE THREAD

**Issue by AlexHx8472** [TrustPoint-Project/trustpoint#75]
Related to [Settings: Security Level Configurations #9](https://github.com/TrustPoint-Project/trustpoint-dev/issues/9)

**Job Story**
When I utilize the Trustoint, I want to be able to select a required security level, so I can enforce the trustpoint comply with the selected level and only provide features that are compliant with this level. (IEC 62443 Security Levels)

**Acceptance Criteria**
- [ ] Must activate / deactivate the local Root CA depending on the security settings
- [ ] The security levels shall comply with and reflect the IEC 62443 security levels
- [x] Add a 'Dev / Debug' Security Setting in which there are no restrictions at all

**Comment by Aircoookie** [comment]
Closing as superseded by #121
